FROM --platform=linux/arm64 debian:bookworm-slim
COPY ./_build/gateryx-client-arm64.deb /tmp/
COPY ./_build/gateryx-server-arm64.deb /tmp/
RUN apt-get update && apt-get install -y libssl3 openssl ca-certificates \
  /tmp/gateryx-client-arm64.deb /tmp/gateryx-server-arm64.deb && \
    rm -f /tmp/*.deb
ENTRYPOINT ["/usr/sbin/gateryx-server"]
