#!/bin/sh

( systemctl stop gateryx > /dev/null 2>&1 || exit 0 )
( systemctl disable gateryx > /dev/null 2>&1 || exit 0 )
( userdel gateryx > /dev/null 2>&1 || exit 0 )

rm -f /etc/logrotate.d/gateryx
